[build]
  command = "npm run build"
  publish = "out_publish"
  functions = "out_functions"

[dev]
  command = "npm run dev:netlify"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "out_publish"
  exclude = ['./out_publish/404.html']
  baseUrl = "https://explorers.netlify.com"
